# Generated by Django 4.2.9 on 2024-01-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_alter_commentlike_profile_alter_postlike_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics', verbose_name='profile_pic'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='post_images', verbose_name='Image'),
        ),
    ]
