# Generated by Django 4.2.9 on 2024-01-24 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0004_profile_friends_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='profile',
        ),
        migrations.AddField(
            model_name='userpost',
            name='liked',
            field=models.ManyToManyField(related_name='likes', to='social_media.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'img'])], verbose_name='profile_pic'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='post_images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'img'])], verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
