# Generated by Django 4.2.9 on 2024-01-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0006_postlike_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to='social_media.profile'),
        ),
    ]
