# Generated by Django 4.2.9 on 2024-01-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0008_alter_postlike_post_alter_userpost_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='liked_comment',
            field=models.ManyToManyField(blank=True, related_name='commentlikes', to='social_media.profile'),
        ),
    ]
