# Generated by Django 4.2.9 on 2024-01-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0010_remove_userpost_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to='social_media.profile'),
        ),
    ]
